# ~/.config/hypr/conf/autostart.conf

# Autostart necessary processes
exec-once = waybar
exec-once = dunst &
exec-once = hypridle
exec-once = waypaper --restore
exec-once = kdeconnectd &
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprsunset