# ~/.config/hypr/conf/input.conf

# Input devices
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
    }
}

# Gestures
gestures {
    gesture = 3, horizontal, workspace
}

# Per-device config
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}